### ISSUE TITLE
Sublime is alive (EDIT by wuub: not really, but will merge PRs either way :-))

### ISSUE THREAD

**Issue by kirillsalykin** [wuub/SublimeREPL#396]
Just wanted to point that sublime is under developing. maybe not that heavy, but...

So, maybe you'll start to receive pull-requests? :)

**Comment by wuub** [comment]
Where did you get that idea? :)

**Comment by kirillsalykin** [comment]
the last commit was on 29 august...
maybe you are right, and thats only my hopes.

But whatever, it would be good if you inlude pull request that fixes pry compatibility, thanks :)

**Comment by wuub** [comment]
If you follow the changelog closely, you'll notice that nothing significant happened since v3052 (23 July 2013), just bugfixes and some small and questionable additions (icons, image preview).

From where I'm standing ST itself is on hold for ~18 months.

Merging a pull request into SublimeREPL is rather painless process most of the time. What's not so quick is preparing a release. 

ST2+ST3 compatibility is never checked by the submitter, and cross platform issues are checked very rarely. 

Since SublimeREPL does not have any kind of automated testing, each release requires manual check on at leas 8 different setups:  [win7|win8|linux|osx] + [st2|st3]. Which is very time consuming.


Since some rather harmless pull requests have piled up since I put the disclaimer on, I might consider a one time merge+release for the community soon.

**Comment by kirillsalykin** [comment]
@wuub what is your editor of choice? cause looks like investing time in ST3 is just waste of time.

**Comment by wuub** [comment]
ST3 and vim. 

I feel comfortable with both and don't plan do drop ST just because it's not maintained. As long as it works on my machine I'll benefit from it and the hours I put in learning about its internals.

But if sublimehq keeps up the current approach, ST will go defunct sooner or later and because of that I prefer to allocate my free time to other projects.

**Comment by kirillsalykin** [comment]
It's me again, sorry.

Did you try https://github.com/limetext/lime? Do you think it's a proper replace for ST?

Do you think it is possible that ST become open source after sublimehq stop development (like Textmate did)?

Sorry me for being intrusive, just figure out what text editor stick to.
VIM and emacs seems too archaic as for me.

**Comment by wuub** [comment]
> It's me again, sorry.
No problem :) 

>Did you try https://github.com/limetext/lime? 
A very, very long time ago

> Do you think it's a proper replace for ST
I don't know. Depends on what you consider essential. 

> Sorry me for being intrusive, just figuring out what text editor stick to.
Does it really matter so much which editor you use? Pick one and just use it. Or better yet pick one w/ GUI and one terminal based. Doesn't really matter that much which ones you pick, as long as you get familiar with them :)

**Comment by chipotle** [comment]
Sublime is actually under fairly active development again, from all appearances, with four or five new dev builds in the last month and new features being added, not just bug fixes, as well as the author showing up on the forums more visibly again.

Whether or not you consider that "active enough" is subjective, but SublimeREPL is useful enough that it would be nice to see it not fall into decay. In addition to a fair number of pull requests, there are people just making their own personal forks which might be valuable to the project (for instance, using `trampoline` for the Clojure REPL).

**Comment by wuub** [comment]
I want to to get back to SublimeREPL as soon as possible, which suddenly became difficult in February since I'm moving after living in one place for ~7 years :)

But I began merging some PR's already, so stay tuned :)
