### ISSUE TITLE
python don't auto wrap word when output too long.

### ISSUE THREAD

**Issue by eromoe** [wuub/SublimeREPL#449]
output is too long,  overflow editor width.
need auto wrap word.

**Comment by Tony36051** [comment]
I have the same problem!

**Comment by Chris-May** [comment]
This might a preference issue. It has always wrapped for me, but I enabled word wrapping in my preferences.

You will probably enable it by going to View > Word Wrap

**Comment by eromoe** [comment]
@Chris-May You are right. Thank you !

**Comment by Tony36051** [comment]
@Chris-May  Thank you !  but I have to manually click this.  Is there a way to do it automatically?

**Comment by Chris-May** [comment]
If I understand what you mean, you sure can. You can add it to your user preferences with: `"word_wrap": true`. This will be a global change, and this is what I do, since It's rare that I don't want word wrap.

If there's a time when you don't want word wrap, you can put `"word_wrap": false` in a syntax-specific preference file.

This and more is explained in the [Sublime Settings documentation](http://www.sublimetext.com/docs/3/settings.html). But let me know if you'd like any more help.

**Comment by minispeck** [comment]
for anyone who finds this and only wants word wrap for the repl and nothing else, you add `"word_wrap": true` to this setting https://github.com/wuub/SublimeREPL/blob/master/SublimeREPL.sublime-settings#L50

closing and reopening the REPL tab is enough after the change, no need to close and reopen sublime
